M48
; DRILL file {KiCad 7.0.0-rc1-unknown-00d77f624a~164~ubuntu22.04.1} date dom 15 ene 2023 10:56:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-15T10:56:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-rc1-unknown-00d77f624a~164~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X116.3Y-77.3
X148.3Y-122.4
X179.8Y-77.4
T0
M30
